### ISSUE TITLE
Running on Ubuntu through SSH connection causes screen/memory corruption

### ISSUE THREAD

**Issue by mchaisso** [broadinstitute/IGV#67]
I'm not sure if this is an issue with ssfs or IGV, but it only shows problems when running IGV.

I am running IGV 2.3.20 (22) on Ubuntu 13.04, loading a file that is on a remote server, mounted locally through sshfs.  Tooltips will frequently not disappear and cause the exception shown below, and the screen will become corrupt after a short while either scrolling or tabbing to another application. 

An example of the corrupt screen cause from tabbing is below.

![igv-screenshot1](https://f.cloud.github.com/assets/1372990/1447640/80538652-424a-11e3-96bf-42db3cea7e07.png)
java.lang.ClassCastException: javax.swing.Popup$HeavyWeightWindow cannot be cast to javax.swing.JComponent
	at javax.swing.ToolTipManager.initiateToolTip(ToolTipManager.java:402)
	at javax.swing.ToolTipManager.mouseEntered(ToolTipManager.java:395)
	at java.awt.Component.processMouseEvent(Component.java:6297)
	at java.awt.Component.processEvent(Component.java:6053)
	at java.awt.Container.processEvent(Container.java:2045)
	at java.awt.Window.processEvent(Window.java:1945)
	at java.awt.Component.dispatchEventImpl(Component.java:4649)
	at java.awt.Container.dispatchEventImpl(Container.java:2103)
	at java.awt.Window.dispatchEventImpl(Window.java:2587)
	at java.awt.Component.dispatchEvent(Component.java:4475)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:675)
	at java.awt.EventQueue.access$300(EventQueue.java:96)
	at java.awt.EventQueue$2.run(EventQueue.java:634)
	at java.awt.EventQueue$2.run(EventQueue.java:632)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:119)
	at java.awt.EventQueue$3.run(EventQueue.java:648)
	at java.awt.EventQueue$3.run(EventQueue.java:646)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:645)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)

**Comment by jrobinso** [comment]
Performance on remote servers over X11 is poor, this is a known issue we unfortunately don't have a solution for.   If possible using a VNC server is recommended to X11.
