### ISSUE TITLE
IGV Web Start Launch Error. Hostname cant be null

### ISSUE THREAD

**Issue by chirayugoswami** [broadinstitute/IGV#82]
Hi I am trying to launch IGV using a HTML link. On my personal computer I am getting this error

java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(Unknown Source)
	at java.net.InetSocketAddress.<init>(Unknown Source)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:650)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
	at org.broad.igv.util.HttpUtils.openConnectionHeadOrGet(HttpUtils.java:270)
	at org.broad.igv.util.HttpUtils.resourceAvailable(HttpUtils.java:246)
	at org.broad.igv.util.FileUtils.resourceExists(FileUtils.java:80)
	at org.broad.igv.feature.genome.GenomeManager.getUserDefinedGenomeArchiveList(GenomeManager.java:962)
	at org.broad.igv.feature.genome.GenomeManager.buildGenomeItemList(GenomeManager.java:868)
	at org.broad.igv.ui.IGVCommandBar.initializeGenomeList(IGVCommandBar.java:175)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2422)
	at org.broad.igv.util.LongRunningTask.submit(LongRunningTask.java:42)
	at org.broad.igv.ui.IGV.startUp(IGV.java:2389)
	at org.broad.igv.ui.Main.open(Main.java:224)
	at org.broad.igv.ui.Main.main(Main.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

The link works fine from other computers. What should i do to not get this error

**Comment by jrobinso** [comment]
I just disable the "SNI" extension fro the next release, which will be 2.3.47.   I do not have an easy means to test the solution however.
